'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const {Store,assert,text,within,atomic,hash,disk}=require('./core.cjs');const {Media,validatePlan}=require('./media.cjs');const {composeNarrated,transcriptPlan}=require('./editor.cjs');const {captureWalkthrough}=require('./walkthrough.cjs');
class Service {
 constructor(root,options={}){this.store=new Store(root,options);this.media=new Media(options);this.running=new Map();this.progress={};this.options=options;}
 assertEditable(pid){const p=this.store.get(pid);assert(!['Recording','Paused','Stopping'].includes(p.state),'Finish the recording before editing or processing this project');assert(!this.running.has(pid),'This project is already processing');return p;}
 async task(pid,stage,fn){this.assertEditable(pid);assert(!this.running.has(pid),'This project is already processing');this.store.claim(pid,'Processing');const controller=new AbortController();this.running.set(pid,controller);this.store.update(pid,'Processing',{error:null});try{const r=await fn(controller.signal);this.store.update(pid,'Needs Review',{error:null});return r;}catch(e){this.store.update(pid,controller.signal.aborted?'Interrupted':'Failed',{error:e.message});throw e;}finally{this.running.delete(pid);delete this.progress[pid];}}
 status(pid){return {project:this.store.get(pid),jobs:this.store.jobs(pid),events:this.store.events(pid),progress:this.progress[pid]||null};}
 cancel(pid){assert(this.running.has(pid),'No cancellable local task is running');this.running.get(pid).abort();return {cancelRequested:true};}
 async walkthrough(pid,options){return this.task(pid,'capture',async signal=>{const manifest=await captureWalkthrough({root:this.store.dir(pid),...options,signal,onProgress:p=>this.progress[pid]={...this.progress[pid],...p}});this.store.update(pid,'Needs Review',{manifest:manifest.path,video:manifest.sessions.find(s=>s.video)?.video,coverage:manifest.coverage.length,output:null,outputKind:null});return manifest;});}
 async process(pid,action){return this.task(pid,action,async signal=>{const p=this.store.get(pid),root=this.store.dir(pid),opts={signal,onProgress:p=>this.progress[pid]={stage:action,detail:p.slice(-180)}};let result;if(action==='remux'){const source=p.data.video;assert(source,'Import a video first');result=await this.media.remux(root,source,opts);}else if(action==='render'){assert(p.data.editPlan,'Review an edit plan first');result=await this.media.render(root,p.data.editPlan,opts);}else if(action==='narrated'){assert(p.data.narratedPlan,'Save a narration plan first');result=await composeNarrated(this.media,root,p.data.narratedPlan,opts);}else if(action==='voice-only'){result=await this.media.voiceOnly(root,p.data.output?.file||p.data.video,p.data.narration,opts);}else throw new Error('Unknown media action');this.store.update(pid,'Needs Review',{output:result,outputKind:action});return result;});}
 saveNarrationPlan(pid,segments){this.assertEditable(pid);assert(Array.isArray(segments)&&segments.length<=40,'Invalid narration plan');for(const s of segments){within(this.store.dir(pid),s.video,true);within(this.store.dir(pid),s.audio,true);}atomic(within(this.store.dir(pid),'narration-plan.json'),segments);return this.store.update(pid,'Needs Review',{narratedPlan:segments,output:null,outputKind:null});}
 transcript(pid,words){const p=this.store.get(pid),source=p.data.video||p.data.output?.file;assert(source,'Import a video first');const plan=transcriptPlan(source,words);return this.savePlan(pid,plan);}
 savePlan(pid,plan){this.assertEditable(pid);validatePlan(plan);within(this.store.dir(pid),plan.source,true);atomic(within(this.store.dir(pid),'edit-plan.json'),plan);return this.store.update(pid,'Needs Review',{editPlan:plan,output:null,outputKind:null});}
 evidence(pid){const p=this.store.get(pid);if(!p.data.manifest)return null;return JSON.parse(fs.readFileSync(within(this.store.dir(pid),p.data.manifest,true),'utf8'));}
 async importFile(pid,source,kind='video'){this.assertEditable(pid);assert(['video','audio','captions'].includes(kind),'Invalid import kind');assert(fs.statSync(source).isFile(),'Not a file');assert(new Set(['.mp4','.mkv','.webm','.mov','.wav','.mp3','.m4a','.srt','.vtt']).has(path.extname(source).toLowerCase()),'Unsupported media type');const root=this.store.dir(pid);disk(root,fs.statSync(source).size+64*1024**2);const rel='imports/'+crypto.randomUUID()+path.extname(source).toLowerCase(),target=within(root,rel);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(source,target,fs.constants.COPYFILE_EXCL);const data={file:rel,sha256:await hash(target)};this.store.update(pid,'Needs Review',kind==='video'?{video:rel,imported:data,output:null,outputKind:null}:kind==='audio'?{narration:rel,output:null,outputKind:null}:{captions:rel});return data;}
 async importProject(source){const manifest=JSON.parse(fs.readFileSync(path.join(source,'project.json'),'utf8'));assert(manifest&&typeof manifest.name==='string'&&['record','walkthrough'].includes(manifest.mode),'Invalid exported project');const p=this.store.create(manifest.name+' (imported)',manifest.mode),root=this.store.dir(p.id);try{const walk=async(dir,rel='')=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){assert(!e.isSymbolicLink(),'Project import cannot contain symlinks');const r=rel?rel+'/'+e.name:e.name;if(r==='project.json')continue;if(e.isDirectory()){fs.mkdirSync(within(root,r));await walk(path.join(dir,e.name),r);}else{assert(/\.(mp4|mkv|webm|mov|wav|mp3|m4a|json|md|srt|vtt|jpg|png|txt)$/i.test(r),'Unsupported file in project export');const input=within(source,r,true);disk(root,fs.statSync(input).size+64*1024**2);await fs.promises.copyFile(input,within(root,r),fs.constants.COPYFILE_EXCL);}}};await walk(source);const history=path.join(source,'job-history.json');if(fs.existsSync(history)){const jobs=JSON.parse(fs.readFileSync(history,'utf8'));assert(Array.isArray(jobs)&&jobs.length<10000,'Invalid job history');for(const j of jobs){assert(typeof j.stage==='string'&&typeof j.fingerprint==='string'&&Number.isFinite(j.cap)&&Number.isFinite(j.estimate),'Invalid imported job');const state=j.state==='Processing'?'Unknown':j.state;this.store.db.prepare('INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),p.id,j.stage,j.fingerprint,state,j.cap,j.estimate,JSON.stringify(j.data||{}),new Date().toISOString());}}const data=manifest.data||{};if(data.video&&data.sourceSha256)assert(await hash(within(root,data.video,true))===data.sourceSha256,'Imported video checksum mismatch');return this.store.update(p.id,'Needs Review',{...data,warning:'Imported project. Review source checksums and provider history before continuing.',error:null});}catch(e){this.store.update(p.id,'Failed',{error:e.message});throw e;}}
 async exportProject(pid,destination){assert(!this.running.has(pid)&&!['Recording','Paused','Stopping'].includes(this.store.get(pid).state),'Finish recording/processing before export');const root=this.store.dir(pid);assert(!path.resolve(destination).startsWith(path.resolve(root)+path.sep),'Export destination cannot be inside this project');assert(!fs.existsSync(destination),'Choose a new export folder to preserve existing outputs');return this.task(pid,'export',async signal=>{const staging=destination+'.partial';assert(!fs.existsSync(staging),'Partial export already exists');fs.mkdirSync(staging,{recursive:true});try{const walk=async(dir,rel='')=>{for(const ent of fs.readdirSync(dir,{withFileTypes:true})){assert(!signal.aborted,'Export cancelled; originals preserved');assert(!ent.isSymbolicLink(),'Project export cannot contain symlinks');const r=rel?rel+'/'+ent.name:ent.name;if(/\.partial|\.tmp|browser-profile|credentials/i.test(r)||r==='project.json')continue;const target=path.join(staging,r);if(ent.isDirectory()){fs.mkdirSync(target);await walk(path.join(dir,ent.name),r);}else{this.progress[pid]={stage:'Exporting',detail:r};await require('node:stream/promises').pipeline(fs.createReadStream(within(root,r,true)),fs.createWriteStream(target,{flags:'wx'}),{signal});}}};await walk(root);const p=this.store.get(pid);atomic(path.join(staging,'project.json'),{...p,state:'Needs Review'});atomic(path.join(staging,'job-history.json'),this.store.jobs(pid));fs.renameSync(staging,destination);return {destination};}catch(e){throw new Error(e.message+' Incomplete export remains in the .partial folder; source files were not changed.');}});}

 async close(){for(const c of this.running.values())c.abort();this.store.close();}
}
module.exports={Service};
