'use strict';
const fs=require('node:fs');const path=require('node:path');const dns=require('node:dns/promises');
const {chromium}=require('playwright');const {assert,atomic,within,disk,id,hash}=require('./core.cjs');
const {publicAddress}=require('./server-egress.cjs');
function privateIP(ip){return !publicAddress(ip);}
async function allowedURL(raw,localOrigin){const u=new URL(raw);assert(['http:','https:'].includes(u.protocol)&&!u.username&&!u.password,'Use an HTTP(S) URL without embedded credentials');if(localOrigin&&u.origin===localOrigin)return u;const addresses=await dns.lookup(u.hostname.replace(/^\[|\]$/g,''),{all:true});assert(addresses.length&&!addresses.some(x=>privateIP(x.address)),'Private network access requires explicit approval of this exact origin');return u;}
function instrument(){
 window.__obsEvidence={started:performance.now(),samples:[],events:[]};
 const record=e=>{const x=e.target;window.__obsEvidence.events.push({type:e.type,at:performance.now(),selector:x?.id?'#'+x.id:x?.tagName,property:e.propertyName||null,elapsed:e.elapsedTime||null});};
 for(const name of ['animationstart','animationend','transitionrun','transitionend'])document.addEventListener(name,record,true);
 let last=0;
 function sample(t){if(t-last>=30){last=t;const e=window.__obsEvidence;if(e.samples.length<20000){e.samples.push({at:t,scrollY:window.scrollY,elements:[...document.querySelectorAll('[id],header,section')].slice(0,50).map(el=>{const c=getComputedStyle(el),r=el.getBoundingClientRect();return {target:el.id?'#'+el.id:el.tagName,transform:c.transform,opacity:c.opacity,position:c.position,top:c.top,x:r.x,y:r.y,width:r.width,height:r.height};}),animations:document.getAnimations().slice(0,40).map(a=>{const target=a.effect?.target;const timing=a.effect?.getTiming();return {target:target?.id?'#'+target.id:target?.tagName,currentTime:typeof a.currentTime==='number'?a.currentTime:null,playState:a.playState,timing:timing?{delay:timing.delay,duration:timing.duration,easing:timing.easing,iterations:Number.isFinite(timing.iterations)?timing.iterations:null}:null,keyframes:a.effect?.getKeyframes().map(k=>Object.fromEntries(Object.entries(k).filter(([key])=>!['computedOffset'].includes(key))))};})});}}requestAnimationFrame(sample);}requestAnimationFrame(sample);
}
async function inventory(page){return page.evaluate(()=>{const selector=e=>e.id?'#'+CSS.escape(e.id):e.getAttribute('data-vistralo-id')?'[data-vistralo-id="'+e.getAttribute('data-vistralo-id')+'"]':null;let n=0;const all=[...document.querySelectorAll('h1,h2,h3,section,header,nav,button,a,summary,[role="tab"],[aria-expanded],[aria-haspopup],canvas,iframe,video')].slice(0,200);return all.map(e=>{if(!e.id)e.setAttribute('data-vistralo-id','e'+n++);const c=getComputedStyle(e),r=e.getBoundingClientRect();return {selector:selector(e),tag:e.tagName,label:(e.innerText||e.getAttribute('aria-label')||'').trim().slice(0,120),role:e.getAttribute('role'),expanded:e.getAttribute('aria-expanded'),rect:{x:r.x,y:r.y,width:r.width,height:r.height},style:{fontFamily:c.fontFamily,fontSize:c.fontSize,lineHeight:c.lineHeight,fontWeight:c.fontWeight,letterSpacing:c.letterSpacing,textAlign:c.textAlign,display:c.display,margin:c.margin,borderRadius:c.borderRadius,gridTemplateColumns:c.gridTemplateColumns,color:c.color,background:c.backgroundColor,gap:c.gap,padding:c.padding,position:c.position,top:c.top,transition:c.transition,animation:c.animation},limitation:['CANVAS','IFRAME','VIDEO'].includes(e.tagName)?'Visual evidence only; internal behavior may be inaccessible':null};});});}
async function captureWalkthrough({root,url,proxy,pages=[],viewports=[{width:1440,height:900}],localApproved=false,actions=[],signal,onProgress=()=>{},channel,executablePath,headless=true,reducedMotion=false,launchArgs=[],chromiumSandbox=false,browserEnv}){
 const parsed=new URL(url),localOrigin=localApproved?parsed.origin:null;await allowedURL(url,localOrigin);assert(Array.isArray(pages)&&pages.length<=4,'At most five pages per capture');assert(viewports.length>=1&&viewports.length<=3,'Choose 1–3 viewports');assert(actions.length<=20,'At most twenty reviewed interactions');
 const urls=[url,...pages.map(p=>new URL(p,url).href)];for(const u of urls){assert(new URL(u).origin===parsed.origin,'Selected pages must share the approved origin');await allowedURL(u,localOrigin);}
 for(const v of viewports)assert(Number.isInteger(v.width)&&Number.isInteger(v.height)&&v.width>=320&&v.width<=1920&&v.height>=320&&v.height<=1200,'Invalid viewport');
 const runId=id().slice(0,8),base=`evidence/${runId}`;fs.mkdirSync(within(root,base),{recursive:true});disk(root,256*1024**2);
 const stableArgs=['--hide-scrollbars','--force-device-scale-factor=1'];
 const launch={headless,proxy,args:[...new Set([...launchArgs,...stableArgs])],chromiumSandbox,env:browserEnv,downloadsPath:within(root,base+'/blocked-downloads')};if(channel)launch.channel=channel;if(executablePath)launch.executablePath=executablePath;
 const browser=await chromium.launch(launch);const abort=()=>browser.close().catch(()=>{});signal?.addEventListener('abort',abort,{once:true});
 const manifest={version:1,id:runId,url,created:new Date().toISOString(),engine:'Playwright Chromium evidence recorder',model:null,claims:[],sessions:[],scope:{urls,viewports,actions:actions.map(a=>({selector:a.selector,trigger:a.trigger})),reducedMotion},limits:['Only selected pages and discovered behaviors within the bounded exploration are covered.','Frame timestamps are capture request times; browser video offset is approximate, not frame-accurate.','DOM timing describes exposed Web Animations metadata, not proof of hidden JavaScript implementation.','Canvas and cross-origin frames need manual visual review.'],coverage:[]};
 try {for(const target of urls)for(const viewport of viewports){
  if(signal?.aborted)throw new Error('Cancelled');const sid='s'+manifest.sessions.length,folder=`${base}/${sid}`;fs.mkdirSync(within(root,folder),{recursive:true});
  const context=await browser.newContext({viewport,screen:viewport,deviceScaleFactor:1,recordVideo:{dir:within(root,folder),size:viewport},reducedMotion:reducedMotion?'reduce':'no-preference',serviceWorkers:'block',acceptDownloads:false});
  await context.route('**/*',async route=>{try{const req=route.request();if(!['GET','HEAD','OPTIONS'].includes(req.method()))return route.abort();await allowedURL(req.url(),localOrigin);if(req.isNavigationRequest()&&new URL(req.url()).origin!==parsed.origin)return route.abort();await route.continue();}catch{await route.abort();}});
  await context.addInitScript(()=>{const style=document.createElement('style');style.textContent='html{overflow-y:scroll;scrollbar-gutter:stable}';document.documentElement.append(style);});
  await context.addInitScript(instrument);const page=await context.newPage();page.on('dialog',d=>d.dismiss());context.on('page',p=>{if(p!==page)p.close();});
  const started=Date.now(),frames=[];let sampling=true,index=0,lastPreview=0;const sampler=(async()=>{while(sampling&&!signal?.aborted){const at=Date.now()-started,file=`${folder}/frame-${String(index++).padStart(5,'0')}.jpg`;try{await page.screenshot({path:within(root,file),type:'jpeg',quality:76,timeout:4000,animations:'allow',caret:'hide',scale:'css'});frames.push({file,at});if(Date.now()-lastPreview>=1000){lastPreview=Date.now();onProgress({preview:file,previewAt:lastPreview});}}catch{}await new Promise(r=>setTimeout(r,1000));}})();
  const session={id:sid,url:target,viewport,reducedMotion,frames,behaviors:[]};manifest.sessions.push(session);
  const plan={done:0,total:0};
  const step=async(label,trigger,selector,action)=>{onProgress({stage:'Capturing',detail:label,step:plan.done,steps:plan.total,session:manifest.sessions.length-1,sessions:urls.length*viewports.length});plan.done++;const before=Date.now()-started;let state='captured',error=null;const domBefore=await page.evaluate(()=>({scrollY,animations:document.getAnimations().length}));try{await action();await page.waitForTimeout(900);}catch(e){state='blocked';error=String(e.message).split('\n')[0].slice(0,180);}const after=Date.now()-started;session.behaviors.push({id:`${sid}-b${session.behaviors.length}`,label,trigger,selector,state,startMs:before,endMs:after,before:domBefore,after:await page.evaluate(()=>({scrollY,animations:document.getAnimations().length})).catch(()=>null),error});};
  try{
   onProgress({stage:'Loading page',detail:target,session:manifest.sessions.length-1,sessions:urls.length*viewports.length});
   await page.goto(target,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1400);session.title=await page.title();session.inventory=await inventory(page);session.behaviors.push({id:sid+'-load',label:'Initial page entrance',trigger:'navigation',selector:'document',state:'captured',startMs:0,endMs:Date.now()-started});
   const total=await page.evaluate(()=>Math.min(document.documentElement.scrollHeight-innerHeight,6000));
   const increment=Math.max(200,Math.floor(viewport.height*.7));
   const hover=session.inventory.filter(e=>e.tag==='BUTTON'||e.tag==='A'||e.tag==='SUMMARY').slice(0,6);
   // Every interaction is known now, so progress can be reported against a real total.
   plan.total=Math.floor(total/increment)+1+2+hover.length+actions.length;
   const scrollTo=y=>page.evaluate(target=>new Promise(resolve=>{let settled=false;const finish=()=>{if(settled)return;settled=true;resolve();};window.addEventListener('scrollend',finish,{once:true});window.scrollTo({top:target,behavior:'smooth'});setTimeout(finish,1600);}),y);
   for(let y=0;y<=total;y+=increment)await step('Scroll down','scroll','document',()=>scrollTo(y));
   await step('Scroll to bottom','scroll','document',()=>scrollTo(total));
   await step('Scroll back upward','scroll-reverse','document',()=>scrollTo(0));
   for(const item of hover)await step('Hover '+item.label,'hover',item.selector,()=>page.locator(item.selector).first().hover({timeout:2500}));
   for(const a of actions){assert(['hover','focus','click','replay'].includes(a.trigger),'Unsupported interaction');assert(typeof a.selector==='string'&&a.selector.length<300,'Invalid selector');if(a.trigger==='click')assert(a.reviewed===true,'Click requires explicit review');await step(a.label||`${a.trigger} ${a.selector}`,a.trigger,a.selector,async()=>{const loc=page.locator(a.selector).first();if(a.trigger==='click'){const safe=await loc.evaluate(e=>!e.closest('form')&&!['INPUT','A'].includes(e.tagName)&&!(/buy|purchase|delete|submit|save|send|pay|order|login|log in|sign in/i.test(e.innerText||'')));assert(safe,'Forms, navigation and potentially destructive controls are blocked');await loc.click({timeout:3000});}else if(a.trigger==='focus')await loc.focus();else if(a.trigger==='replay')await page.reload({waitUntil:'domcontentloaded'});else await loc.hover({timeout:3000});});}
   session.measurements=await page.evaluate(()=>window.__obsEvidence);
   for(const item of session.inventory){const b=session.behaviors.filter(b=>b.selector===item.selector);manifest.coverage.push({session:sid,selector:item.selector,label:item.label,state:item.limitation?'blocked':b.length?'captured':'discovered',reason:item.limitation||(!b.length?'No targeted interaction tested':null)});}
  }catch(e){session.error=String(e.message).split('\n')[0];manifest.coverage.push({session:sid,selector:'document',state:'blocked',reason:session.error});}
  finally{sampling=false;await sampler;const video=page.video();await context.close();if(video){const file=await video.path();session.video=path.relative(root,file).split(path.sep).join('/');session.videoSha256=await hash(file);}}
  atomic(within(root,base+'/motion-manifest.json'),manifest);
 }}finally{signal?.removeEventListener('abort',abort);await browser.close();}
 if(signal?.aborted)throw new Error('Cancelled; captured evidence remains on disk');
 for(const s of manifest.sessions){for(const b of s.behaviors){const samples=(s.measurements?.samples||[]).filter(t=>t.at>=b.startMs&&t.at<=b.endMs);const animations=samples.flatMap(x=>x.animations);b.visualSamples=samples.filter((_,i)=>i%3===0).map(x=>({at:x.at,scrollY:x.scrollY,elements:x.elements}));b.observedAnimations=[...new Map(animations.map(a=>[JSON.stringify([a.target,a.timing,a.keyframes]),a])).values()];b.evidence=s.frames.filter(f=>f.at>=b.startMs-200&&f.at<=b.endMs+200).map(f=>f.file);b.confidence='requires visual review';b.timingBasis='measured browser metadata when present; no exact duration inferred from sparse screenshots';b.implementationProposal=null;manifest.claims.push(b);}}
 manifest.path=base+'/motion-manifest.json';atomic(within(root,manifest.path),manifest);writeBrief(root,manifest);return manifest;
}
function writeBrief(root,m){const lines=[`# Website implementation brief`,``, `Source: ${m.url}`,`Captured: ${m.created}`,``, `## Scope and limitations`,...m.limits.map(x=>'- '+x),``,`This local report contains recorded observations. AI interpretation and narration have not run unless an analysis file is separately present.`,``,`## Recorded behavior`];for(const s of m.sessions){lines.push(``,`### ${s.title||s.url} — ${s.viewport.width} × ${s.viewport.height}`,``,`Original-speed video: [recording](${s.video?.split('/').slice(-2).join('/')||''})`);for(const b of s.behaviors){lines.push(``,`#### ${b.label}`,`- Trigger: ${b.trigger}; target: \`${b.selector}\`; state: ${b.state}.`,`- Evidence window: ${(b.startMs/1000).toFixed(2)}–${(b.endMs/1000).toFixed(2)} s from capture start; approximate video offset.`,`- Exposed animations: ${b.observedAnimations.length}. ${b.timingBasis}.`);for(const a of b.observedAnimations.slice(0,8))lines.push(`- Measured metadata for \`${a.target}\`: ${JSON.stringify(a.timing)}. Keyframe easing: ${(a.keyframes||[]).map(k=>k.easing).join(' → ')}. Changes: ${JSON.stringify(a.keyframes)}. Properties: ${[...new Set((a.keyframes||[]).flatMap(k=>Object.keys(k)))].join(', ')}.`);for(const f of b.evidence.filter((_,i)=>i%5===0))lines.push(`- [Frame](${f.split('/').slice(-2).join('/')})`);lines.push(`- Implementation proposal: pending review; no library inferred.`);}}
 atomic(within(root,path.dirname(m.path)+'/implementation-brief.md'),lines.join('\n'));atomic(within(root,path.dirname(m.path)+'/coverage-report.json'),m.coverage);
}
module.exports={captureWalkthrough,allowedURL,privateIP,writeBrief,inventory};
